exports.seed = function (knex) {
    return knex('items').insert([
        { name: 'basket', description: 'great for carrying produce', price: 4, category: '', location: '', user_id: 1 },
        { name: 'necklace', description: 'handmade, beautiful!', price: 88, category: '', location: '', user_id: 1 },
        { name: 'table', description: 'large for 6 people', price: 12, category: '', location: '', user_id: 2 },
        { name: 'chair', description: 'white oak', price: 85, category: '', location: '', user_id: 2 },
        { name: 'doll', description: 'hand stitched', price: 7, category: '', location: '', user_id: 3 },
        { name: 'painting', description: 'kilimanjaro landscape', price: 49, category: '', location: '', user_id: 3 },
        { name: 'sculpture', description: 'wildlife art', price: 56, category: '', location: '', user_id: 4 },
        { name: 'tomatoes', description: 'delicious 2 lb bag', price: 47, category: '', location: '', user_id: 4 },
        { name: 'potatoes', description: '5 lbs', price: 42, category: '', location: '', user_id: 5 },
        { name: 'papaya', description: 'ripe in season', price: 33, category: '', location: '', user_id: 5 },
        { name: 'knive set', description: 'hand crafted, wooden handles', price: 99, category: '', location: '', user_id: 6 },
        { name: 'chicken feed', description: '50 lb sack', price: 16, category: '', location: '', user_id: 6 },
        { name: 'shirt', description: 'colorful designs, all sizes', price: 24, category: '', location: '', user_id: 7 },
        { name: 'skirt', description: 'handmade, long and short', price: 64, category: '', location: '', user_id: 7 },
        { name: 'dress', description: 'formal gown', price: 100, category: '', location: '', user_id: 8 },
        { name: 'pants', description: 'cotton, many sizes', price: 50, category: '', location: '', user_id: 8 },
        { name: 'hat', description: 'block the sun and look good too', price: 20, category: '', location: '', user_id: 9 },
        { name: 'sandals', description: 'leather hand crafted', price: 30, category: '', location: '', user_id: 9 },
        { name: 'shoes', description: 'many sizes and colors', price: 25, category: '', location: '', user_id: 10 },
        { name: 'toy blocks', description: 'great for your kids', price: 10, category: '', location: '', user_id: 10 },
        { name: 'jerry can', description: 'great for carrying water', price: 7, category: '', location: '', user_id: 11 },
        { name: 'ring', description: 'ruby and gold band', price: 400, category: '', location: '', user_id: 11 },
        { name: 'pillow', description: 'cool!', price: 41, category: '', location: '', user_id: 12 },
        { name: 'blanket', description: 'awesome!', price: 53, category: '', location: '', user_id: 12 },
        { name: 'plates', description: 'excellent!', price: 24, category: '', location: '', user_id: 13 },
        { name: 'cups', description: 'fantastic!', price: 26, category: '', location: '', user_id: 13 },
        { name: 'frying pan', description: 'amazing!', price: 78, category: '', location: '', user_id: 14 },
        { name: 'fire wood', description: 'perfect!', price: 94, category: '', location: '', user_id: 14 },
        { name: 'bicycle', description: 'cool beanz', price: 34, category: '', location: '', user_id: 15 },
        { name: 'corn', description: 'outstanding!', price: 37, category: '', location: '', user_id: 15 },
        { name: 'chipati', description: 'delicious!', price: 17, category: '', location: '', user_id: 16 },
        { name: 'eggs', description: 'a dozen', price: 12, category: '', location: '', user_id: 16 },
        { name: 'grain', description: '50 lb sack', price: 4, category: '', location: '', user_id: 17 },
        { name: 'solar panel', description: 'awesome!', price: 500, category: '', location: '', user_id: 17 },
        { name: 'laptop', description: 'amazing!', price: 9, category: '', location: '', user_id: 18 },
        { name: 'bricks', description: 'excellent!', price: 65, category: '', location: '', user_id: 18 },
        { name: 'couch', description: 'fantastic!', price: 27, category: '', location: '', user_id: 19 },
        { name: 'lamp', description: 'perfect!', price: 32, category: '', location: '', user_id: 19 },
        { name: 'bottle', description: 'outstanding!', price: 3, category: '', location: '', user_id: 20 },
        { name: 'lumber', description: 'teak and ebony', price: 74, category: '', location: '', user_id: 20 },
        { name: 'motorbike', description: 'go fast', price: 850, category: '', location: '', user_id: 21 },
        { name: 'chainsaw', description: 'yessss', price: 270, category: '', location: '', user_id: 21 },
        { name: 'flamethrower', description: 'go nuts!', price: 390, category: '', location: '', user_id: 22 },
        { name: 'movies', description: 'from China', price: 44, category: '', location: '', user_id: 22 },
        { name: 'phone', description: 'with wifi', price: 210, category: '', location: '', user_id: 23 },
        { name: 'pencils', description: '10 pack', price: 5, category: '', location: '', user_id: 23 },
        { name: 'paper', description: '100 pack', price: 46, category: '', location: '', user_id: 24 },
        { name: 'bookshelf', description: 'medium size, two shelves', price: 47, category: '', location: '', user_id: 24 },
        { name: 'wardrobe', description: 'very large', price: 80, category: '', location: '', user_id: 25 },
        { name: 'rug', description: 'big size for living space', price: 60, category: '', location: '', user_id: 25 },
        { name: 'hammer', description: 'awesome!', price: 50, category: '', location: '', user_id: 26 },
        { name: 'saw', description: 'amazing!', price: 70, category: '', location: '', user_id: 26 },
        { name: 'shovel', description: 'fantastic!', price: 18, category: '', location: '', user_id: 27 },
        { name: 'mattress', description: 'excellent!', price: 13, category: '', location: '', user_id: 27 },
        { name: 'curtains', description: 'outstanding!', price: 11, category: '', location: '', user_id: 28 },
        { name: 'ball', description: 'for playing football', price: 7, category: '', location: '', user_id: 28 },
        { name: 'crossbow', description: 'sharpshooter!', price: 99, category: '', location: '', user_id: 29 },
        { name: 'axe', description: 'chop that wood!', price: 22, category: '', location: '', user_id: 29 },
        { name: 'bike tire', description: 'mister fix it', price: 6, category: '', location: '', user_id: 30 },
        { name: 'wheelbarrow', description: 'haul stuff on the farm', price: 73, category: '', location: '', user_id: 30 },
    ]);
};